#!/bin/bash
# author : mannahoc
# script : print wal colorscheme 

# import colors from wal
. "${HOME}/.cache/wal/colors.sh"

# set colors
f=3 b=4
for j in f b; do
    for i in {0..7}; do
        printf -v $j$i %b "\e[${!j}${i}m"
    done
done
t=$'\e[0m'

# output
cat << EOF
 
 $b1       $t   $b2       $t   $b3       $t   $b4       $t   $b5       $t   $b6       $t   $b7       $t

 $f1$color1$t   $f2$color2$t   $f3$color3$t   $f4$color4$t   $f5$color5$t   $f6$color6$t   $f7$color7$t

EOF
