#!/bin/sh
#
# lemonbar
#
# wm tool

a="%{F#FF99A1}"
t="%{F-}"

wks() {
    var=$(bspc wm -g | grep -o '[OFU][1-7]' | tail -c2)
    for i in $(seq 1 6); do
        if [ "$var" -eq "$i" ]; then
            line="$line$a$t"
        else
            line="$line"
        fi
    done
    echo "$line"
}

clk() {
    var=$(date +'%a %R')
    echo "$a$t $var"
}

net() {
    var=$(iwgetid -r)
    echo "$a$t ${var:-Offline}"
}

vol() {
    var=$(amixer sget Master)
    if echo "$var" | grep -q off; then
        echo "$a$t Muted"
    else
        var=$(echo "$var" | grep -om1 '[0-9]*%')
        echo "$a$t $var"
    fi
}

bat() {
    var=$(acpi | awk '{print $4}' | tr -d '%')
    if [ "$var" -eq 100 ]; then
        echo "$a$t $var%"
    elif [ "$var" -gt 75 ]; then
        echo "$a$t $var%"
    elif [ "$var" -gt 25 ]; then
        echo "$a$t $var%"
    else
        echo "$a$t $var%"
    fi
}

while echo "%{S1}%{l}  $(wks)%{c}$(clk)%{r}$(net)  $(vol)  $(bat)  "
do sleep .2s
done |\
    lemonbar -g 1280x28+640+1080 \
    -f "Wuncon Siji-8" \
    -f "xos4 Terminus-8" \
    -B \#0A0606 \
    -F \#DcD6D6
