#!/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        4
bspc config window_gap          16

bspc config focused_border_color \#f0f0f0
bspc config normal_border_color \#151515

bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_follows_pointer	true
bspc config click_to_focus		true
bspc config center_pseudo_tiled		false
bspc config single_monocle		true
bspc config pointer_modifier		mod1

$HOME/.screenlayout/xrandr-i3.sh
nitrogen --restore &
compton --config $HOME/.config/compton/compton.conf &
polybar laptop &
