#! /bin/sh

sxhkd &
$HOME/.fehbg &
$HOME/.screenlayout/xrandr-i3.sh &
polybar -c $HOME/.config/polybar/config -r laptop &
compton -fcC &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         	3
bspc config window_gap          	8
bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true
